# Migration file generated by Django on 2024-03-07 10:50.
# This migration alters model options for the 'News' model.

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            # Setting verbose name plural for better readability.
            options={'verbose_name_plural': 'News'},
        ),
    ]
