# Generated by Django 5.0.2 on 2024-02-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(max_length=256)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('places_count', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.types')),
            ],
        ),
    ]
