# Generated by Django 5.0.2 on 2024-03-13 07:12

import datetime
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('places_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(max_length=256)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/events/')),
                ('date', models.DateField(default=datetime.date(1970, 1, 1))),
                ('is_available', models.BooleanField(default=True)),
                ('available_places', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventlocation')),
            ],
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.types'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', django.db.models.functions.datetime.Now())), name='event_date_future'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('available_places__gte', 0)), name='positive_available_places'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'date'), name='unique_event_title_date'),
        ),
        migrations.AddConstraint(
            model_name='eventlocation',
            constraint=models.CheckConstraint(check=models.Q(('places_count__gt', 0)), name='event_places_count_positive'),
        ),
    ]
