# Generated by Django 5.0.2 on 2024-03-06 14:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventlocation'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', django.db.models.functions.datetime.Now())), name='event_date_future'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'date'), name='unique_event_title_date'),
        ),
        migrations.AddConstraint(
            model_name='eventlocation',
            constraint=models.CheckConstraint(check=models.Q(('places_count__gte', 0)), name='event_places_count_positive'),
        ),
    ]
