# Generated by Django 5.0.2 on 2024-03-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_location_alter_eventlocation_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE event_event
                DROP COLUMN available_places;
                
                ALTER TABLE event_event
                ADD COLUMN available_places INTEGER DEFAULT NULL;
            """
        ),
    ]

