# Generated by Django 5.0.2 on 2024-03-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_available_places_count_calculation'),
        ('event', '0004_0003_changes'),
    ]

    operations = [
    ]
