# Generated by Django 5.0.2 on 2024-03-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_merge_20240306_2310'),
    ]

    operations = [
        migrations.RunSQL(
            sql=
            """
            CREATE OR REPLACE FUNCTION update_event_availability() RETURNS TRIGGER AS $$
            BEGIN
                -- Update the is_available status based on event date and available places
                UPDATE event_event
                SET is_available = CASE 
                                    WHEN date >= CURRENT_DATE AND available_places > 0 THEN TRUE
                                    ELSE FALSE
                                END
                WHERE id = NEW.id;
                
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            
            """
            )
    ]
    
