# Generated by Django 5.0.2 on 2024-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_update_event_availability_improved'),
    ]

    operations = [
        # Updates the plural name for the Types model to "Types" for the Django admin.
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name_plural': 'Types'},
        ),
        # Sets the default value of the is_available field in the Event model to True.
        migrations.AlterField(
            model_name='event',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
