# Generated by Django 5.0.2 on 2024-03-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_update_event_availability_improved'),
    ]

    operations = [
        migrations.RunSQL(
            sql=
            """
            DROP TRIGGER event_update_after ON event_event

            CREATE TRIGGER event_after_insert_or_update
            AFTER INSERT OR UPDATE OF date, available_places ON event_event
            FOR EACH ROW
            EXECUTE FUNCTION update_event_availability();

            
            """
            )
    ]
