# Generated by Django 5.0.2 on 2024-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_types_options_alter_event_is_available'),
    ]

    # Intergrate available places as a model variable

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_places',
            field=models.IntegerField(),
        ),
    ]
