# Generated by Django 5.0.2 on 2024-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_available_places'),
    ]

    operations = [
        # Default value and constraint 
        
        migrations.AlterField(
            model_name='event',
            name='available_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('available_places__gte', 0)), name='positive_available_places'),
        ),
    ]
