# Generated by Django 5.0.2 on 2024-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_available_places_and_more'),
    ]

    # Deleted the default property
    
    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_places',
            field=models.IntegerField(),
        ),
    ]
