# Generated by Django 5.0.2 on 2024-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_available_places_initial_setter'),
    ]

    # Now places_count should be at least 1
    
    operations = [
        migrations.RemoveConstraint(
            model_name='eventlocation',
            name='event_places_count_positive',
        ),
        migrations.AddConstraint(
            model_name='eventlocation',
            constraint=models.CheckConstraint(check=models.Q(('places_count__gt', 0)), name='event_places_count_positive'),
        ),
    ]
