# Migration file generated by Django on 2024-03-03 16:01.
# This migration creates a SQL function and a trigger to verify ticket validity.

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial')
    ]

    operations = [
        # Creating a SQL function to verify ticket validity.
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION verify_ticket_validity()
                RETURNS TRIGGER AS $$
                BEGIN
                    -- Check if the event associated with the ticket is valid (not outdated) and available.
                    IF NOT EXISTS (
                        SELECT 1 FROM event_event
                        WHERE event_event.id = NEW.event_id
                        AND event_event.is_available = TRUE
                    ) THEN
                        -- Raise an exception if the event is not valid or available.
                        RAISE EXCEPTION 'Event not valid or not available';
                    END IF;
                    -- Return the new ticket if validation passes.
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                -- Creating a trigger to check ticket validity before insertion or update.
                CREATE TRIGGER trigger_check_user_ticket_validity
                BEFORE INSERT OR UPDATE ON user_ticket
                FOR EACH ROW EXECUTE FUNCTION verify_ticket_validity();
            """
        ),
    ]
