# Generated by Django 5.0.2 on 2024-03-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial')
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION verify_ticket_validity()
                RETURNS TRIGGER AS $$
                BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM event_event
                    WHERE event_event.id = NEW.event_id
                    AND event_event.is_available = TRUE
                    AND event_event.date > CURRENT_DATE
                ) THEN
                    RAISE EXCEPTION 'Event not valid or not available';
                END IF;
                RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER trigger_check_user_ticket_validity
                BEFORE INSERT OR UPDATE ON user_ticket
                FOR EACH ROW EXECUTE FUNCTION verify_ticket_validity();
            """
        ),
    ]
