# Generated by Django 5.0.2 on 2024-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240303_1801'),
    ]

    operations = [
        migrations.RunSQL(sql=
        """
            CREATE OR REPLACE FUNCTION verify_ticket_validity()
            RETURNS TRIGGER AS $$
            BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM event_event
                WHERE event_event.id = NEW.event_id
                AND event_event.is_available = TRUE
                AND event_event.date > CURRENT_DATE
                AND (SELECT 1 from user_customuser WHERE user_customuser.id = NEW.user_id)
            ) THEN
                RAISE EXCEPTION 'Event or user not available or not valid';
            END IF;
            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)
    ]
