# Migration file generated by Django on 2024-03-06 14:46.
# This migration alters the 'user' foreign key field in the 'Ticket' model and adds a check constraint for positive place values.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_adding_constraints'),
        ('user', '0002_verify_ticket_validity_trigger'),
    ]

    operations = [
        # Altering the 'user' foreign key field in the 'Ticket' model to use CASCADE deletion behavior.
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # Adding a check constraint to ensure that the 'place' field in the 'Ticket' model has a positive value.
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('place__gte', 0)), name='ticket_place_positive'),
        ),
    ]
