# Migration file generated by Django on 2024-03-06 17:59.
# This migration alters the foreign key fields 'event' and 'user' in the 'Ticket' model to use CASCADE deletion behavior and adds related names for reverse querying.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_adding_constraints'),
        ('user', '0004_alter_ticket_user_ticket_ticket_place_positive'),
    ]

    operations = [
        # Altering the 'event' foreign key field in the 'Ticket' model to use CASCADE deletion behavior and adding a related name for reverse querying.
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='event.event'),
        ),
        # Altering the 'user' foreign key field in the 'Ticket' model to use CASCADE deletion behavior and adding a related name for reverse querying.
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
