# Generated by Django 5.0.2 on 2024-03-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_ticket_event_alter_ticket_user'),
        ('user', '0006_auto_20240306_2017'),
    ]

    operations = [
    ]
